# mariner-installer main configuration file
# note current configuration is written to mariner-installer.yaml every time mariner-installer is run

## Installer configuration
:name: mariner-installer
# Path to answer file
:answer_file: /etc/foreman/mariner-installer.answers.yaml

# Load puppet modules from a specific path
:modules_dir: /usr/share/foreman-installer/modules
:installer_dir: /usr/share/foreman-installer

# Logging config
:log_dir: /var/log/mariner-installer
:log_name: mariner-installer.log
:log_level: :debug

## Kafo tuning, customization of core functionality
:order: 
  - foreman
  - foreman_proxy
  - puppet

# The mapping hash provides Kafo with the information to find plugin classes
:mapping: {}
